name: investment_app
description: A simplified stock viewer.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.0.0
  syncfusion_flutter_charts: ^28.2.5+1
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  shared_preferences: ^2.1.0
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/crown.png
    - assets/castle.png
    - assets/images/stocks/
    - assets/images/grass_texture.png
    - assets/images/house.png
    - assets/images/shop.png
    - assets/images/windmill.png
    - assets/logos/
  fonts:
    - family: CinzelDecorative
      fonts:
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
          weight: 700
